name: bantuin
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  intl: ^0.20.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  geolocator: ^14.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  firebase_messaging: ^15.2.5
  http: ^1.2.2
  flutter_local_notifications: ^19.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.0.7 
  firebase_storage: ^12.4.6 
  url_launcher  : ^6.2.6
  rxdart: ^0.27.7
  flutter_launcher_icons: ^0.13.1 
  cloud_functions: ^5.5.1
  webview_flutter: ^4.8.0
  firebase_performance: ^0.10.1+10
  google_maps_flutter: ^2.10.0
  flutter_polyline_points: ^2.1.0
  crypto: ^3.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/googlelogo.png
    - assets/images/logobantuin.svg
    - assets/images/email_icon.svg
    - assets/images/kendaraan.png
    - assets/images/elektronik.png
    - assets/images/mobil2.jpeg
    - assets/images/bintang.JPG
    - assets/images/fotochat.jpg
    - assets/images/Mbarang.svg
    - assets/images/Mpenghasilan.svg
    - assets/images/pelayanan.svg
    - assets/images/vehicles/mobil/bak.png
    - assets/images/mobil.png
    - assets/images/vehicles/mobil/sedan.png
    - assets/images/vestic.png
    - assets/images/vehicles/mobil/family.png
    - assets/images/workshop.png
    - assets/images/mobil_bmw.png
    - assets/images/office.png
    - assets/images/profile.png
    - assets/images/oli.png
    - assets/images/telpon.png
    - assets/images/rider.png
    - assets/images/motor.png
    - assets/images/otw.png
    - assets/images/diperbaiki.png
    - assets/images/cari.png
    - assets/images/selesai.png
    - assets/images/bayar.png
    - assets/images/vehicles/motor/bebek.png
    - assets/images/vehicles/motor/matic.png
    - assets/images/vehicles/motor/cruiser.png
    - assets/images/vehicles/motor/Trail.png
    - assets/images/vehicles/mobil/sport.png
    - assets/images/ban.png
    - assets/images/mogok.png
    - assets/images/ac.png
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/banner3.png
    - assets/images/beranda.png
    - assets/images/pesanan.png
    - assets/images/pesan.png
    - assets/images/pengaturan.png
    - assets/images/backgroundselesai.png
    - assets/images/chat.png
    - assets/images/penghasilan.png
    - assets/images/layanan.png
    - assets/images/ulasan2.png
    - assets/images/barang.png

    - assets/images/elektronik/rumahtangga/dapur.png
    - assets/images/elektronik/rumahtangga/pembersih.png
    - assets/images/elektronik/rumahtangga/pendingin.png
    - assets/images/elektronik/kantor/audio dan visual.png
    - assets/images/elektronik/kantor/hp dan aksesoris.png
    - assets/images/elektronik/kantor/komputer dan aksesoris.png
    - assets/images/elektronik/kantor/lain-lain.png
    - assets/images/elektronik/rumah tangga.png
    - assets/images/elektronik/kantor.png
    - assets/images/elektronik/layanan/perawatan.png
    - assets/images/elektronik/layanan/perbaikan mesin.png
    - assets/images/elektronik/layanan/perbaikan layar.png
    - assets/images/elektronik/layanan/instalasi.png
    - assets/images/elektronik/layanan/lain-lain.png
    - assets/images/status_completed.png
    - assets/images/status_processing.png
    - assets/images/status_work_done.png
    - assets/images/status_rejected.png
    - assets/images/status_default.png
    - assets/images/status_pending.png
    - assets/images/porsche.png
    - assets/images/asap.png
    - assets/images/bantuin.png
    - assets/images/animasi.png
    - assets/images/email.png
    - assets/images/email2.png
    - assets/images/logo_bantuin.png
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
